### ISSUE TITLE
Issue during build

### ISSUE THREAD

**Issue by sridhargopinath** [DynamicCodeSearch/CodeSeer#5]
Hi,

I ran into the following issue while building the project using Maven.

```
Downloading from maven2: http://repo1.maven.org/maven2/edu/ncsu/codeseer/projects/1.0-SNAPSHOT/projects-1.0-SNAPSHOT.pom
...
[ERROR] Failed to execute goal on project code: Could not resolve dependencies for project edu.ncsu.codeseer:code:jar:1.0-SNAPSHOT: Failed to collect dependencies at edu.ncsu.codeseer:projects:jar:1.0-SNAPSHOT: 
Failed to read artifact descriptor for edu.ncsu.codeseer:projects:jar:1.0-SNAPSHOT: Could not transfer artifact edu.ncsu.codeseer:projects:pom:1.0-SNAPSHOT from/to maven2 (http://repo1.maven.org/maven2): Transfe
r failed for http://repo1.maven.org/maven2/edu/ncsu/codeseer/projects/1.0-SNAPSHOT/projects-1.0-SNAPSHOT.pom 501 HTTPS Required -> [Help 1]
[ERROR]
```

I tried to use https instead of http, but the error persisted. I think the issue might be because the following URL is unreachable?
[https://repo1.maven.org/maven2/edu/ncsu/](https://repo1.maven.org/maven2/edu/ncsu/)

Noting that, I commented out the following in `pom.xml` file:
```
<!--<dependency>
    <groupId>edu.ncsu.codeseer</groupId>
    <artifactId>projects</artifactId>
    <version>1.0-SNAPSHOT</version>
    <!-<scope>system</scope>->
    <!-<systemPath>${project.basedir}/jars/projects-1.0-SNAPSHOT-jar-with-dependencies.jar</systemPath>->
</dependency>-->
```
After this change, the build was successful.

I am new to Maven and I am not sure if this is the right change. Can you please let me know?

Thanks,
Sridhar

**Comment by bigfatnoob** [comment]
@sridhargopinath Sridhar,
1. Make sure that you are on the `ICSE20` branch and not on `master` before you build it.
2. `edu.ncsu.codeseer:projects:jar:1.0-SNAPSHOT` is a local dependency and should not lookup in remote maven repository. This jar should exist in the `code/jars` folder. If you run the initialize command, this process is handled. If not, you might want to
    * Build the projects folder using `mvn clean install`
    * Copy the jar into the `code/jars` folder 
     ```
      $> mkdir -p ../code/jars
      $> cp ../projects/target/projects-1.0-SNAPSHOT-jar-with-dependencies.jar ../code/jars/
     ```
You must not comment out that dependency.
Let me know if this helps

**Comment by chrisparnin** [comment]
Should we merge ICSE20 => master?

**Comment by sridhargopinath** [comment]
Hi George,

Thanks for the comments. I was able to run the code on the Example dataset.

There are a few comments that might be helpful to anyone in the future:
1. In Install.md, it is mentioned to run `mvn clean install`. But running this command directly would not be successful as you mentioned in your comments. I ran `initialize.sh` to get around this issue.
2. Python 3 is not supported. There is some syntax used in the code that has been deprecated by Python 3 (like `is not`). Hence, Python 2 is necessary. This becomes a hassle on the latest versions of Ubuntu where Python 2 is not supported anymore.

You can consider adding this to your documents.

BTW, great paper! Enjoyed reading it and loved the idea :)

**Comment by bigfatnoob** [comment]
Thank you Sridhar. Will update the ReadMe with your proposed changes :)
